Update Q3-Type-of-language.md
eliannyscer/Top-100-Python-Interview pull request #1
Opened 2021-06-19 17:28 UTC by eliannyscer

2021-06-19 17:40 UTC, mauragas requested changes

2021-06-19 17:40 UTC, mauragas commented on Q1-Difference-between-list-and-tuples.md
> -* You use round brackets in the syntax: tuple = ("Ellie", 33, 7)
I think you should add more info

2021-06-19 17:42 UTC, eliannyscer commented on Q1-Difference-between-list-and-tuples.md
> -* You use round brackets in the syntax: tuple = ("Ellie", 33, 7)
I will do it tomorrow!

2021-06-25 14:17 UTC, mauragas requested changes

2021-06-25 14:17 UTC, mauragas commented on Q1-Difference-between-list-and-tuples.md
> +`Type` - Are mutable they can be edited, is possible update or delete an item from the list.
```suggestion
`Type` - Are mutable (can be edited), it is possible update or delete an item from the list.
```

2021-06-25 14:17 UTC, mauragas commented on Q1-Difference-between-list-and-tuples.md
> +['Cereal', 'bread', 'avocado', 'beef']
```suggestion
# Output:
# ['Cereal', 'bread', 'avocado', 'beef']
```

2021-06-25 14:17 UTC, mauragas commented on Q1-Difference-between-list-and-tuples.md
> +('Cereal', 'bread', 'avocado', 'beef')
```suggestion
# Output:
# ('Cereal', 'bread', 'avocado', 'beef')
```

2021-06-26 09:34 UTC, merged